### ISSUE TITLE
I couldn't run it in google colab

### ISSUE THREAD

**Issue by licjavierbarrios** [amrrs/ai-content-gen-with-bloom#2]
Hello, I tried to open in google colab but it was about 40 gb download with multiple warnings. From what I see it can't be executed in colab, is that right?

**Comment by amrrs** [comment]
the largest model can't run  on Colab Free Tier. It requires more computation.

**Comment by nicoleahmed** [comment]
when using 1b1 and 1b7 models - i dont get any content in colab - ive used the code exactly as you've written - not sure sure whats going on

**Comment by amrrs** [comment]
@nicoleahmed does it show any error?

**Comment by licjavierbarrios** [comment]
Thanks, I'm now familiar with how it works. I'm going to try it locally at some point!

**Comment by amrrs** [comment]
Thanks for letting me know!
